### ISSUE TITLE
Unclear relationship on high level context diagram

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/Team_Team5_CS-GY-6063-Fall2021#17]
<img width="574" alt="Screen Shot 2021-09-28 at 17 40 57" src="https://user-images.githubusercontent.com/53953892/135169703-38e86cdf-4b8f-474a-88da-c79362c19ed8.png">

"The database" is not an actor yet it shows up on the high level diagram. Please clarify

**Comment by HenryTseTse** [comment]
Updated high level context diagram
