### ISSUE TITLE
Calendar allows events of past date

### ISSUE THREAD

**Issue by Aahbree** [gcivil-nyu-org/Team_Team5_CS-GY-6063-Fall2021#210]
When I tried creating a calendar event, it allows me to create an event for past dates.

Document states:
Create Calendar Event Page: https://smashteam5.herokuapp.com/event/new/
Able to type or select a date from the small calendar in the “Start Time” and “End Time” input fields (An error message will occur when trying to submit a date/time that has already passed)

![team5.jpg](https://images.zenhubusercontent.com/614ddca82371e5170d31d27f/34954a07-96b2-4c02-b263-32eace803b1b)

Ideas for improvement: Add validation for start date. You have already added a validation that the end time cannot be earlier than the start time, so past dates will not be used even for the end date

**Comment by MithraR** [comment]
Closed this issue
