### ISSUE TITLE
Post 0 food availability 

### ISSUE THREAD

**Issue by Aahbree** [gcivil-nyu-org/Team_Team5_CS-GY-6063-Fall2021#221]
As a restaurant owner, I should be able to post food availability with 1 or more meals. However, I'm allowed to post even 0 meals.![Screen Shot 2021-11-18 at 4.55.10 PM.png](https://images.zenhubusercontent.com/614ddca82371e5170d31d27f/41297b8a-3e43-4a15-b10b-7916b9788e0a)

**Comment by HenryTseTse** [comment]
This is actually not a bug, we are allowing restaurants to update their food availability as they are giving away meals. They should be allowed to show that there are no more meals for the day. However, there might be a better way to show that there is no meals left, thanks for the feedback
