### ISSUE TITLE
Edit Profile - no checks for address/phone number validity

### ISSUE THREAD

**Issue by Aahbree** [gcivil-nyu-org/Team_Team5_CS-GY-6063-Fall2021#222]
The address field in edit profile page allows random address. Phone number allows more than 10 digits.![Screen Shot 2021-11-18 at 4.47.01 PM.png](https://images.zenhubusercontent.com/614ddca82371e5170d31d27f/81411e86-2a8e-400e-8ac9-88bc9288d380)

Ideas for improvement:
Add field validation or maybe make it a non required field

**Comment by sri-harsh** [comment]
Resolved the phone number part.
