### ISSUE TITLE
Wrong error message in while creating event from Calendar. 

### ISSUE THREAD

**Issue by VISHDIVGAU** [gcivil-nyu-org/Team_Team5_CS-GY-6063-Fall2021#224]
I tried creating a event without title and description but with correct start and end times. But each time error message I am getting is "Start time must be before end time" instead of missing required fields.. Please see the SS.

![team5issue2.png](https://images.zenhubusercontent.com/614e108cc19f8ac004baa3cc/6d3f4feb-15ca-45b2-8e7b-8482ee743c6e)

![team5issue2part2.png](https://images.zenhubusercontent.com/614e108cc19f8ac004baa3cc/ce48ab7e-152e-4586-b5a6-cf24c13cf180)

**Comment by sri-harsh** [comment]
Resolved!
