### ISSUE TITLE
Creating event validation (duplicate bug)

### ISSUE THREAD

**Issue by marcuspoon2** [gcivil-nyu-org/Team_Team5_CS-GY-6063-Fall2021#228]
Creating an event with nothing in the title and description, but with correct dates entered will give a "Start time must be before end time" error even though the error is that of empty text fields

https://user-images.githubusercontent.com/67922103/142682482-3ff968e6-faf9-4835-9e77-116a2e05d541.mov

**Comment by barksdaleaz** [comment]
Resolved
