### ISSUE TITLE
adding a post creates an error

### ISSUE THREAD

**Issue by marcuspoon2** [gcivil-nyu-org/Team_Team5_CS-GY-6063-Fall2021#229]
Posting a blog post brings you to an error page, but the post is still there on the Posts tab.

Recreate:
1. Login
2. click add post
3. type the post and enter it
4. you'll see an error page
5. go back and click posts
6. you'll see the post on the list of posts

https://user-images.githubusercontent.com/67922103/142683608-f62813f2-eef3-4285-9c59-a1c04783c44e.mov

**Comment by sri-harsh** [comment]
Resolved!
