### ISSUE TITLE
Food Redistributor able to delete another distributor's calendar event 

### ISSUE THREAD

**Issue by marcuspoon2** [gcivil-nyu-org/Team_Team5_CS-GY-6063-Fall2021#230]
A food redistributor is able to delete other distributor's calendar events if they hardcode the delete url into the browser

Recreate:
1. log into prof redis account (logins for user1 aren't working)
2. create event on calendar
3. check that it's there on calendar
4. save delete url 
5. logout
6. login as testuser2
7. verify you can't delete event on calendar
8. paste delete url in browser
9. confirm delete
10. verify on calendar

Uploading Screen Recording 2021-11-19 at 2.59.13 PM.mov…

**Comment by marcuspoon2** [comment]
first video was long so not sure it loaded. Here's a shorter one that hopefully uploads:

https://user-images.githubusercontent.com/67922103/142685647-a2b86e93-6999-4c94-9b7e-c95411bda9bb.mov

**Comment by sri-harsh** [comment]
Resolved.
