### ISSUE TITLE
No option to update/delete food availability as a restraunt

### ISSUE THREAD

**Issue by marcuspoon2** [gcivil-nyu-org/Team_Team5_CS-GY-6063-Fall2021#232]
You're able to post food availability as expected, but there should be an option to update the amount and an option to delete the post in the case that you run out. Otherwise it could be misleading if the post is up until the end date, yet they have no food

**Comment by barksdaleaz** [comment]
![image](https://user-images.githubusercontent.com/59379235/142687622-b9756812-09c9-4c36-a4e3-4b794897b1b7.png)
Known issue.
