### ISSUE TITLE
several minor bugs

### ISSUE THREAD

**Issue by Scott-Canning** [gcivil-nyu-org/Team_Team5_CS-GY-6063-Fall2021#233]
restaurant != restuarant (url/tab)
![image.png](https://images.zenhubusercontent.com/614dcca8f2879f4a3e254cbb/f944c608-cdf9-43c3-b381-1e50fad1f9e0)

Overlapped text when failed login/click out of text box
![image](https://user-images.githubusercontent.com/34758484/142693887-6651e499-3700-4114-b872-b21e2ecec2b7.png)

Error page after adding post (item still posted):
![image.png](https://images.zenhubusercontent.com/614dcca8f2879f4a3e254cbb/140db7a9-1f6b-4b16-b931-a61ec8067799)

![image.png](https://images.zenhubusercontent.com/614dcca8f2879f4a3e254cbb/e9f06e66-e4c8-4350-ba5f-c64ee422ef14)

![image.png](https://images.zenhubusercontent.com/614dcca8f2879f4a3e254cbb/fbd1b89e-1d8c-417e-999f-72f86ff7b8e0)

**Comment by sri-harsh** [comment]
Resolved!
