### ISSUE TITLE
creating a new calendar event : doesn't prompt what are the essential fields, throws a wrong error. 

### ISSUE THREAD

**Issue by Simran-Shandilya** [gcivil-nyu-org/Team_Team5_CS-GY-6063-Fall2021#235]
![image](https://user-images.githubusercontent.com/64326729/142707412-0b009713-8c67-4844-b772-5644b27f8a13.png)
![image](https://user-images.githubusercontent.com/64326729/142707515-62c04c73-e2b7-4436-a74e-f52cff6511c7.png)

**Comment by barksdaleaz** [comment]
Resolved
